export default function MainPanelBody(): JSX.Element {
  return (
    <>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
      <div>MainPanelBody</div>
    </>
  )
}
