CREATE TABLE IF NOT EXISTS nodes (
  id TEXT PRIMARY KEY,
  parent_id TEXT REFERENCES nodes(id) ON DELETE SET NULL ON UPDATE CASCADE,
  index TEXT NOT NULL,
  attribute_ids TEXT NOT NULL DEFAULT '[]',
  title TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  type_id TEXT REFERENCES node_types(id) ON DELETE SET NULL ON UPDATE CASCADE
)